compressionLevel: mixed

enableGlobalCache: true

enableTelemetry: false

enableConstraintsChecks: true

nodeLinker: node-modules

npmRegistryServer: 'https://registry-npm.cbhq.net'

npmScopes:
  cbhq:
    npmRegistryServer: 'https://registry-npm.cbhq.net'

yarnPath: .yarn/releases/yarn-4.0.2.cjs
